# Generated by Django 5.2.10 on 2026-01-21 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('violation_alert', 'Rule Violation Alert'), ('deadline_reminder', 'Deadline Reminder'), ('advancement_result', 'Advancement Result'), ('submission_reviewed', 'Submission Reviewed'), ('team_invitation', 'Team Invitation'), ('comment_reply', 'Comment Reply'), ('post_liked', 'Post Liked'), ('new_follower', 'New Follower'), ('system_announcement', 'System Announcement')], db_index=True, max_length=50, verbose_name='Notification Type')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Notification content', verbose_name='Message')),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to related content', max_length=500, verbose_name='Link URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data specific to notification type (JSON)', verbose_name='Metadata')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('sent_email', models.BooleanField(default=False, help_text='Whether email notification was sent', verbose_name='Sent Email')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
