# Generated by Django 5.2.10 on 2026-01-22 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('wagtailcore', '0098_delete_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('violation_alert', 'Rule Violation Alert'), ('deadline_reminder', 'Deadline Reminder'), ('advancement_result', 'Advancement Result'), ('submission_reviewed', 'Submission Reviewed'), ('team_invitation', 'Team Invitation'), ('comment_reply', 'Comment Reply'), ('post_liked', 'Post Liked'), ('new_follower', 'New Follower'), ('system_announcement', 'System Announcement'), ('login_success', 'Login Success'), ('hackathon_created', 'New Hackathon Created')], db_index=True, max_length=50, verbose_name='Notification Type'),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('enabled_types', models.JSONField(blank=True, default=dict, help_text="Format: {'type_key': true/false}", verbose_name='Enabled Notification Types')),
                ('default_in_app', models.BooleanField(default=True, help_text='Enable in-app notifications by default', verbose_name='Default In-App Notifications')),
                ('default_email', models.BooleanField(default=False, help_text='Enable email notifications by default', verbose_name='Default Email Notifications')),
                ('notify_content_owner', models.BooleanField(default=True, help_text='Include content creators in notifications about their own content', verbose_name='Notify Content Owner')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
