# Generated by Django 5.2.10 on 2026-01-21 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_add_locale'),
        ('wagtailcore', '0098_delete_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='navigationsettings',
            unique_together={('translation_key', 'locale')},
        ),
    ]
