# Generated by Django 5.2.10 on 2026-01-21 05:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_add_translatable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopic',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='authorsnippet',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
