# Generated by Django 5.2.10 on 2026-01-21 09:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('community', '0001_initial'),
        ('images', '0001_initial'),
        ('wagtailcore', '0098_delete_embed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed at the top of the teams listing page')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Team Index Page',
                'verbose_name_plural': 'Team Index Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TeamProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('tagline', models.CharField(blank=True, help_text='Short team description or motto', max_length=500, verbose_name='Tagline')),
                ('is_open_for_members', models.BooleanField(default=True, help_text='Show in team formation and accept join requests', verbose_name='Open for New Members')),
                ('max_members', models.PositiveIntegerField(default=10, help_text='Maximum number of team members allowed', verbose_name='Maximum Members')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('django_group', models.OneToOneField(blank=True, editable=False, help_text='Auto-created Django Group for team permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to='auth.group')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Logo')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Team Profile',
                'verbose_name_plural': 'Team Profiles',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('hacker', 'Hacker (Engineer)'), ('hipster', 'Hipster (Designer/UX)'), ('hustler', 'Hustler (Business/Marketing)'), ('mentor', 'Mentor'), ('member', 'Member')], default='member', help_text='Team role', max_length=50, verbose_name='Role')),
                ('is_leader', models.BooleanField(default=False, help_text='Team captain/leader', verbose_name='Is Leader')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships_new', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('team', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.teamprofilepage')),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'ordering': ['-is_leader', 'joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
