# Generated by Django 5.2.10 on 2026-01-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0009_add_hackathon_tags_and_index_filters'),
        ('home', '0002_create_homepage'),
        ('news', '0002_rename_newslistingpage_to_newsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hackathons_items_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of hackathons to display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hackathons_section_page',
            field=models.ForeignKey(blank=True, help_text='Select the Hackathon Index Page to display hackathons from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hackathons.hackathonindexpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hackathons_section_title',
            field=models.CharField(default='Featured Hackathons', help_text='Title for the hackathons section on the home page', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_items_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of news articles to display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_section_page',
            field=models.ForeignKey(blank=True, help_text='Select the News Index Page to display articles from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.newsindexpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_section_title',
            field=models.CharField(default='Latest News', help_text='Title for the news section on the home page', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_stats_section',
            field=models.BooleanField(default=True, help_text='Show the statistics section (active hackathons, teams, quests)'),
        ),
    ]
