# Generated by Django 5.2.10 on 2026-01-21 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0004_submission_copyright_declaration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('purchase', 'Purchased'), ('transfer_in', 'Received Transfer'), ('transfer_out', 'Sent Transfer'), ('redeem', 'Redeemed'), ('expire', 'Expired')], db_index=True, max_length=50, verbose_name='Transaction Type')),
                ('asset_type', models.CharField(max_length=50, verbose_name='Asset Type')),
                ('asset_id', models.CharField(max_length=200, verbose_name='Asset ID')),
                ('quantity', models.IntegerField(help_text='Positive for gain, negative for loss', verbose_name='Quantity')),
                ('description', models.TextField(blank=True, help_text='Transaction description', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_sent', to=settings.AUTH_USER_MODEL, verbose_name='From User')),
                ('related_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathons.quest', verbose_name='Related Quest')),
                ('related_submission', models.ForeignKey(blank=True, help_text='Submission that triggered this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathons.submission', verbose_name='Related Submission')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_received', to=settings.AUTH_USER_MODEL, verbose_name='To User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Asset Transaction',
                'verbose_name_plural': 'Asset Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='assets_asse_user_id_c21333_idx'), models.Index(fields=['transaction_type', '-created_at'], name='assets_asse_transac_b6dc4c_idx'), models.Index(fields=['asset_type', 'asset_id'], name='assets_asse_asset_t_a46f49_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('badge', 'Badge'), ('achievement', 'Achievement'), ('coin', 'Coin'), ('token', 'Token'), ('nft', 'NFT')], db_index=True, max_length=50, verbose_name='Asset Type')),
                ('asset_id', models.CharField(help_text="Identifier for specific asset (e.g., 'first_place_badge')", max_length=200, verbose_name='Asset ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this asset owned', verbose_name='Quantity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional asset properties (rarity, description, image_url)', verbose_name='Metadata')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Acquired At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Asset',
                'verbose_name_plural': 'User Assets',
                'ordering': ['-acquired_at'],
                'indexes': [models.Index(fields=['user', 'asset_type'], name='assets_user_user_id_856e9d_idx'), models.Index(fields=['asset_type', 'asset_id'], name='assets_user_asset_t_0c166c_idx')],
                'unique_together': {('user', 'asset_type', 'asset_id')},
            },
        ),
    ]
