# Generated by Django 5.2.10 on 2026-01-21 05:24

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_round',
            field=models.PositiveIntegerField(default=1, help_text='Current competition round'),
        ),
        migrations.AddField(
            model_name='team',
            name='elimination_reason',
            field=models.TextField(blank=True, help_text='Reason for elimination or disqualification'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('advanced', 'Advanced to Next Round'), ('eliminated', 'Eliminated'), ('disqualified', 'Disqualified')], default='forming', max_length=20),
        ),
        migrations.CreateModel(
            name='CompetitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('team_size', 'Team Size'), ('team_composition', 'Team Composition'), ('submission_format', 'Submission Format'), ('eligibility', 'Participant Eligibility'), ('conduct', 'Code of Conduct'), ('deadline', 'Deadline'), ('other', 'Other')], help_text='Category of this rule', max_length=50, verbose_name='Rule Type')),
                ('title', models.CharField(help_text='Short title for this rule', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the rule', verbose_name='Description')),
                ('rule_definition', models.JSONField(blank=True, default=dict, help_text="Rule configuration as JSON (e.g., {'min_members': 2, 'max_members': 5})", verbose_name='Rule Definition')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether violation leads to disqualification', verbose_name='Is Mandatory')),
                ('penalty', models.CharField(blank=True, choices=[('warning', 'Warning'), ('point_deduction', 'Point Deduction'), ('disqualification', 'Disqualification')], help_text='Consequence of violation', max_length=50, verbose_name='Penalty')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which rules are displayed', verbose_name='Display Order')),
                ('hackathon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hackathons.hackathonpage', verbose_name='Hackathon')),
            ],
            options={
                'verbose_name': 'Competition Rule',
                'verbose_name_plural': 'Competition Rules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvancementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('advanced', 'Advanced to Next Round'), ('eliminated', 'Eliminated')], help_text='Whether team advanced or was eliminated', max_length=20, verbose_name='Decision')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Decision Time')),
                ('notes', models.TextField(blank=True, help_text='Reason for decision or additional notes', verbose_name='Notes')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Staff member who made the decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advancement_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decided By')),
                ('from_phase', models.ForeignKey(blank=True, help_text='Phase team is advancing from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_from', to='hackathons.phase', verbose_name='From Phase')),
                ('team', models.ForeignKey(help_text='Team affected by this decision', on_delete=django.db.models.deletion.CASCADE, related_name='advancement_logs', to='hackathons.team', verbose_name='Team')),
                ('to_phase', models.ForeignKey(blank=True, help_text='Phase team is advancing to (if advanced)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_to', to='hackathons.phase', verbose_name='To Phase')),
            ],
            options={
                'verbose_name': 'Advancement Log',
                'verbose_name_plural': 'Advancement Logs',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['team', '-decided_at'], name='hackathons__team_id_6deb11_idx'), models.Index(fields=['decision'], name='hackathons__decisio_af9f26_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detected At')),
                ('detection_method', models.CharField(choices=[('automated', 'Automated Check'), ('manual', 'Manual Report')], max_length=20, verbose_name='Detection Method')),
                ('description', models.TextField(help_text='Details of the violation', verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('action_taken', models.TextField(blank=True, help_text='What action was taken in response to this violation', verbose_name='Action Taken')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this violation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('rule', models.ForeignKey(help_text='Rule that was violated', on_delete=django.db.models.deletion.CASCADE, to='hackathons.competitionrule', verbose_name='Rule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='hackathons.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Rule Violation',
                'verbose_name_plural': 'Rule Violations',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['team', '-detected_at'], name='hackathons__team_id_e43753_idx'), models.Index(fields=['status'], name='hackathons__status_8729bd_idx')],
            },
        ),
    ]
