# Generated by Django 5.2.10 on 2026-01-21 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_team_current_round_team_elimination_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='approved', max_length=20, verbose_name='Status')),
                ('preferred_role', models.CharField(choices=[('hacker', 'Hacker (Engineer)'), ('hipster', 'Hipster (Designer/UX)'), ('hustler', 'Hustler (Business/Marketing)'), ('any', 'Any Role')], default='any', help_text='Role preference for team formation', max_length=50, verbose_name='Preferred Role')),
                ('is_seeking_team', models.BooleanField(default=True, help_text='Show in team formation page', verbose_name='Seeking Team')),
                ('motivation', models.TextField(blank=True, help_text='Why user wants to participate', verbose_name='Motivation')),
                ('skills', models.JSONField(blank=True, default=list, help_text="User's skills for team matching", verbose_name='Skills')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', verbose_name='Rejection Reason')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='hackathons.hackathonpage', verbose_name='Hackathon')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('team', models.ForeignKey(blank=True, help_text='Team user joined (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='hackathons.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Hackathon Registration',
                'verbose_name_plural': 'Hackathon Registrations',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['hackathon', 'status', '-registered_at'], name='hackathons__hackath_5ea9d1_idx'), models.Index(fields=['user', '-registered_at'], name='hackathons__user_id_8f6430_idx'), models.Index(fields=['hackathon', 'is_seeking_team', 'status'], name='hackathons__hackath_01d305_idx')],
                'unique_together': {('hackathon', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score for technical implementation (0-100)', max_digits=6, verbose_name='Technical Score')),
                ('commercial_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score for business viability (0-100)', max_digits=6, verbose_name='Commercial Score')),
                ('operational_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score for operational feasibility (0-100)', max_digits=6, verbose_name='Operational Score')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall score (calculated or manual)', max_digits=6, verbose_name='Overall Score')),
                ('feedback', models.TextField(blank=True, help_text='Detailed feedback from judge', verbose_name='Feedback')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed scoring criteria as JSON', verbose_name='Score Breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('judge', models.ForeignKey(help_text='Staff member who provided this score', on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores_given', to=settings.AUTH_USER_MODEL, verbose_name='Judge')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to='hackathons.submission', verbose_name='Submission')),
            ],
            options={
                'verbose_name': 'Judge Score',
                'verbose_name_plural': 'Judge Scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', '-created_at'], name='hackathons__submiss_e7dd5d_idx'), models.Index(fields=['judge', '-created_at'], name='hackathons__judge_i_060b1b_idx')],
                'unique_together': {('submission', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='ScoreBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('commercial', 'Commercial'), ('operational', 'Operational')], max_length=50, verbose_name='Category')),
                ('criterion_name', models.CharField(help_text="e.g., 'Code Quality', 'Market Fit', 'Scalability'", max_length=200, verbose_name='Criterion Name')),
                ('description', models.TextField(blank=True, help_text='What this criterion evaluates', verbose_name='Description')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in final score calculation', max_digits=5, verbose_name='Weight')),
                ('max_points', models.PositiveIntegerField(default=100, help_text='Maximum points for this criterion', verbose_name='Maximum Points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='hackathons.hackathonpage', verbose_name='Hackathon')),
            ],
            options={
                'verbose_name': 'Score Breakdown Criterion',
                'verbose_name_plural': 'Score Breakdown Criteria',
                'ordering': ['hackathon', 'category', 'order'],
                'indexes': [models.Index(fields=['hackathon', 'category'], name='hackathons__hackath_4de042_idx')],
            },
        ),
    ]
