# Generated by Django 5.2.10 on 2026-01-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_hackathonregistration_judgescore_scorebreakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='copyright_declaration',
            field=models.BooleanField(default=False, help_text='User confirms ownership or proper licensing of submitted content'),
        ),
        migrations.AddField(
            model_name='submission',
            name='copyright_notes',
            field=models.TextField(blank=True, help_text='Additional copyright information or licensing details'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_transfer_confirmed',
            field=models.BooleanField(default=False, help_text='User confirmed file upload completed successfully'),
        ),
        migrations.AddField(
            model_name='submission',
            name='originality_check_result',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed originality check results (similarity score, sources)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='originality_check_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('checking', 'Checking'), ('pass', 'Passed'), ('warning', 'Warning - Similarity Detected'), ('fail', 'Failed - Plagiarism Detected')], default='not_checked', help_text='Automated originality verification status', max_length=20),
        ),
    ]
