# Generated by Django 5.2.10 on 2026-01-21 05:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_submission_copyright_declaration_and_more'),
        ('wagtailcore', '0098_delete_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed at the top of the hackathons listing page')),
                ('featured_hackathon', models.ForeignKey(blank=True, help_text='Select a hackathon to feature at the top of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hackathons.hackathonpage')),
            ],
            options={
                'verbose_name': 'Hackathon Index Page',
                'verbose_name_plural': 'Hackathon Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
