# Generated by Django 5.2.10 on 2026-01-21 09:04

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


def populate_quest_locale_and_translation_key(apps, schema_editor):
    """Populate locale and translation_key for existing Quest records."""
    Locale = apps.get_model('wagtailcore', 'Locale')
    Quest = apps.get_model('hackathons', 'Quest')

    try:
        en_locale = Locale.objects.get(language_code='en')
    except Locale.DoesNotExist:
        # If no locale exists, create one
        en_locale = Locale.objects.create(language_code='en')

    # Update all existing quests
    for quest in Quest.objects.all():
        if not quest.locale_id:
            quest.locale_id = en_locale.id
        if not quest.translation_key:
            quest.translation_key = uuid.uuid4()
        quest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_refactor_quest_to_snippet'),
        ('images', '0001_initial'),
        ('wagtailcore', '0098_delete_embed'),
    ]

    operations = [
        # Step 1: Populate existing data
        migrations.RunPython(populate_quest_locale_and_translation_key, migrations.RunPython.noop),
        # Step 2: Make fields non-nullable
        migrations.AlterField(
            model_name='quest',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Step 3: Create QuestIndexPage
        migrations.CreateModel(
            name='QuestIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed at the top of the quests listing page')),
                ('featured_quest', models.ForeignKey(blank=True, help_text='Select a quest to feature at the top of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hackathons.quest')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Quest Index Page',
                'verbose_name_plural': 'Quest Index Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
