# Generated by Django 5.2.10 on 2026-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0008_alter_quest_locale_alter_quest_translation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonindexpage',
            name='filter_mode',
            field=models.CharField(choices=[('all', 'All Hackathons'), ('in_progress', 'In Progress Only'), ('by_tag', 'By Tag')], default='all', help_text='How to filter hackathons on this index page', max_length=20),
        ),
        migrations.AddField(
            model_name='hackathonindexpage',
            name='filter_tag',
            field=models.CharField(blank=True, help_text="Tag to filter by (only used when filter_mode is 'by_tag'). E.g., 'from_enterprise'", max_length=100),
        ),
        migrations.AddField(
            model_name='hackathonpage',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for categorization (e.g., ['from_enterprise', 'ai', 'blockchain'])"),
        ),
    ]
