# Generated by Django 5.2.10 on 2026-01-21 09:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_team_profile_page'),
        ('hackathons', '0009_add_hackathon_tags_and_index_filters'),
        ('images', '0001_initial'),
        ('wagtailcore', '0098_delete_embed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('tagline', models.CharField(blank=True, help_text='Short project description (one-liner)', max_length=500, verbose_name='Tagline')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('document', 2), ('image', 3), ('video_url', 4), ('github_repo', 8), ('demo_url', 9), ('code_block', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content'}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a document (PDF, Markdown, etc.)'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Video URL (YouTube, Vimeo, etc.)'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Repository URL'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Description', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'main', 'label': 'Branch', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('url', 5), ('description', 6), ('branch', 7)]], {'help_text': 'GitHub repository link'}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Live demo URL'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('go', 'Go'), ('rust', 'Rust'), ('other', 'Other')]}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('language', 10), ('code', 11)]], {'help_text': 'Code snippet'})}, verbose_name='Content')),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='draft', max_length=20, verbose_name='Status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score (0-100) entered by reviewer', max_digits=6, null=True, verbose_name='Score')),
                ('feedback', models.TextField(blank=True, help_text='Reviewer feedback and comments', verbose_name='Feedback')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('team_profile', models.ForeignKey(help_text='The team submitting this project', on_delete=django.db.models.deletion.PROTECT, related_name='hackathon_submissions', to='community.teamprofilepage', verbose_name='Team')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_submission_pages', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'indexes': [models.Index(fields=['verification_status'], name='hackathons__verific_153733_idx')],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='approved', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text="Team's notes or motivation for joining", verbose_name='Notes')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('hackathon', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='hackathons.hackathonpage')),
                ('team_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_registrations', to='community.teamprofilepage', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Registration',
                'verbose_name_plural': 'Team Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('hackathon', 'team_profile')},
            },
        ),
    ]
