# Generated by Django 5.2.10 on 2026-01-22 02:27

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_team_profile_page'),
        ('hackathons', '0010_add_submission_page_and_team_registration'),
        ('images', '0001_initial'),
        ('wagtailcore', '0098_delete_embed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonpage',
            name='allow_edit_after_submit',
            field=models.BooleanField(default=True, help_text='Participants can edit their submission after submitting', verbose_name='Allow editing after submission'),
        ),
        migrations.AddField(
            model_name='hackathonpage',
            name='allow_late_submission',
            field=models.BooleanField(default=False, help_text='Accept submissions after deadline (may be marked as late)', verbose_name='Allow late submissions'),
        ),
        migrations.AddField(
            model_name='hackathonpage',
            name='max_submissions_per_participant',
            field=models.PositiveIntegerField(default=0, help_text='Maximum submissions allowed per user/team. 0 = unlimited', verbose_name='Max submissions per participant'),
        ),
        migrations.AddField(
            model_name='hackathonpage',
            name='require_registration',
            field=models.BooleanField(default=True, help_text='Participant must register before submitting', verbose_name='Require registration'),
        ),
        migrations.AddField(
            model_name='hackathonpage',
            name='restrict_to_submission_phase',
            field=models.BooleanField(default=True, help_text='Only allow submissions during submission phase', verbose_name='Restrict to submission phase'),
        ),
        migrations.AddField(
            model_name='hackathonpage',
            name='submission_type',
            field=models.CharField(choices=[('individual', 'Individual only'), ('team', 'Team only'), ('both', 'Both allowed')], default='both', help_text='Who can submit to this hackathon', max_length=20, verbose_name='Submission type'),
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='hackathons',
            field=models.ManyToManyField(blank=True, help_text='Hackathons this submission participates in', related_name='submissions', to='hackathons.hackathonpage', verbose_name='Hackathons'),
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='Individual user submitting this project (leave empty for team submission)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_pages', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='submissionpage',
            name='team_profile',
            field=models.ForeignKey(blank=True, help_text='The team submitting this project (leave empty for individual submission)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='community.teamprofilepage', verbose_name='Team'),
        ),
        migrations.CreateModel(
            name='SubmissionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed at the top of the submissions listing page', verbose_name='Introduction')),
                ('enable_hackathon_filter', models.BooleanField(default=True, verbose_name='Enable hackathon filter')),
                ('enable_date_filter', models.BooleanField(default=True, verbose_name='Enable date range filter')),
                ('enable_submitter_filter', models.BooleanField(default=True, verbose_name='Enable submitter filter')),
                ('enable_team_filter', models.BooleanField(default=True, verbose_name='Enable team filter')),
                ('enable_status_filter', models.BooleanField(default=True, verbose_name='Enable status filter')),
                ('default_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], max_length=20, verbose_name='Default status filter')),
                ('default_hackathon', models.ForeignKey(blank=True, help_text='Pre-select a hackathon when page loads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hackathons.hackathonpage', verbose_name='Default hackathon filter')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Submission Index',
                'verbose_name_plural': 'Submission Indexes',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
